### ISSUE TITLE
Add state migration to proposals for the timestamps change 

### ISSUE THREAD

**Issue by blue-note** [DA0-DA0/dao-contracts#408] opened 2022-07-19 19:07 UTC
first determine if current proposal migrations are going to run out of gas

**Comment by Callum-A** [comment] 2022-07-20 16:32
The more I think on this the more I prefer the paginated MigrateMsg approach, as this allows us to iterate over the map and hit all the keys, and we can simply use a `.map()` call with a `.collect()` which should be pretty optimised

**Comment by janitachalam** [comment] 2022-07-22 03:37
I think you were right about the code id thing though, like I don't think wasm migrate will be invoked if the code ID target is the same as what its migrating from? seems like the pagination thing may be going against how migrate was intended to work

**Comment by blue-note** [comment] 2022-08-15 18:41
a bit more update on gas testing for proposal migrations: I found that the gas_used seems to increase linearly with the number of proposals being migrated, with the average gas_used per single proposal migration being 23773.  Which means that with a block max_gas limit of 100_000_000 (https://rpc.uni.juno.deuslabs.fi/consensus_params), we can estimate that we will be able to migrate ~4200 proposals at a time before running out of gas

**Closed** 2022-08-15 20:37 UTC
Labels: v2
